package hack

import (
	"database/sql"

	"github.com/gin-gonic/gin"

	_ "github.com/swaggo/gin-swagger/example/basic/docs" // docs is generated by Swag CLI, you have to import it.
)

type Service struct {
	engine *gin.Engine
	db     *sql.DB
}

func New(dbAdp *sql.DB) *Service {
	return &Service{
		db: dbAdp,
	}
}
