package server

import (
	"github.com/Meexe/gin-example/internal/server/middleware"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/swaggo/gin-swagger/example/basic/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v2

var db = make(map[string]string)

func New() *gin.Engine {
	a := gin.Default()

	public := a.Group("/")
	authorized := a.Group("admin", middleware.Auth)

	// url := ginSwagger.URL("http://localhost:8080/swagger/doc.json")

	public.GET("swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	public.GET("ping", Ping)
	public.GET("user/:name", GetUsername)

	authorized.POST("me", IsAdmin)

	return a
}
