package server

import (
	"database/sql"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/swaggo/gin-swagger/example/basic/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v2

type Server struct {
	engine *gin.Engine
	db     *sql.DB
}

func New(dbAdp *sql.DB) *Server {
	a := gin.Default()

	return &Server{
		engine: a,
		db:     dbAdp,
	}
}

func (s *Server) Run(host string) {
	// url := ginSwagger.URL("http://localhost:8080/swagger/doc.json")

	s.engine.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	s.engine.GET("/ping", s.Ping)
	s.engine.GET("/user/:name", s.GetUsername)
	s.engine.GET("/org-structure", s.GetOrgStructure)
	s.engine.Run(host)
}
